# Generated by Django 4.0.4 on 2022-05-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_acctransaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acctransaction',
            name='account_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
